# Generated by Django 2.2.3 on 2020-02-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='full_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_file', models.CharField(max_length=30)),
                ('date_file', models.DateField()),
                ('country_id', models.CharField(max_length=2)),
            ],
        ),
    ]
